<a href="https://colab.research.google.com/github/Facco-Bruno/python-codes/blob/main/E03_Leitura_de_um_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title
%%capture
!rm *
!gdown --id '1BLyWu9zDytBTGR6vLL-UTSAZhpwRQD6b'
!gdown --id '1a5jY17w-SINzRRdq2iH6SFEQiS_ZaAKj'
!gdown --id '1RmUz5LqBQbfn02hvPdwP4ICpWVfa_bTV'
!gdown --id '1ZkG09pQDz29mOFR5VTMPEirvwClVNj_F'
!gdown --id '14zHXla8960NSNjqzf2j1ip8pFYqGyPRJ'
#!gdown --id '1vWtNHG3ehZyjmWUlP85i9z4u7G7Ror7L'
!gdown --id '1KNQKU68Y_XtFN2AS0guGpKDmiMM3YNij'
!gdown --id '1R9LZJw-lvngWOVSInKNhKNkvTPpuS0KI'
#!gdown --id '1UaAWEmE6Igp7P9C5EQJby_EykEiI_fZ1'
!gdown --id '11vJUJtgumou5hkM1a8TribAXkHDlSpz_'
!gdown --id '1jNFpdEtEbtcMgd51K6pjEvjB0hCFEI_E'
!gdown --id '1dNZ8LvkczzE1oOdh_S7cu3Z5eG4T4EqG'
!pip install git+https://github.com/grading/gradememaybe.git

from IPython.display import YouTubeVideo
from gofer import ok

# 1 Upload do Arquivo

Use o espaço abaixo para fazer o upload do arquivo para o ambiente do Google Colab. Para isso você pode usar o comando `gdown` (lembre-se de colocar o sinal de exclamação `!` para chamar comandos na linha de comando, fora do Python).

In [ ]:
# Seu código aqui
#from google.colab import files

#import io

#uploaded = files.upload()
#f = io.BytesIO(uploaded['Iris.csv'])

In [ ]:
import os
os.path.isfile('/content/Iris.csv')

True

In [ ]:
ok.check('e03_1.py')

# 2 Leitura do Arquivo

Escreva um laço que leia todas as linhas do arquivo, criando uma lista numa variável de nome 'd0', onde cada elemento da lista é uma string que corresponde a uma linha do arquivo.

In [ ]:
# Seu código aqui
f = open('/content/Iris.csv', 'r')
linhas = f.readlines()

d0 = []

for linha in linhas:
   d0.append(linha)

In [ ]:
ok.check('e03_2.py')

# 3 Remoção de Cabeçalho e Contagem de Linhas

Utilizando a mesma variável `d0`, agora remova o cabeçalho (que deve ser o primeiro elemento da lista), e conte as linhas de dados. Grave o total de linhas numa variável de nome `total`.

In [ ]:
# Seu código aqui

d0.pop(0)

total = len(d0)

In [ ]:
ok.check('e03_3.py')

In [ ]:
d0

['1,5.1,3.5,1.4,0.2,Iris-setosa\n',
 '2,4.9,3.0,1.4,0.2,Iris-setosa\n',
 '3,4.7,3.2,1.3,0.2,Iris-setosa\n',
 '4,4.6,3.1,1.5,0.2,Iris-setosa\n',
 '5,5.0,3.6,1.4,0.2,Iris-setosa\n',
 '6,5.4,3.9,1.7,0.4,Iris-setosa\n',
 '7,4.6,3.4,1.4,0.3,Iris-setosa\n',
 '8,5.0,3.4,1.5,0.2,Iris-setosa\n',
 '9,4.4,2.9,1.4,0.2,Iris-setosa\n',
 '10,4.9,3.1,1.5,0.1,Iris-setosa\n',
 '11,5.4,3.7,1.5,0.2,Iris-setosa\n',
 '12,4.8,3.4,1.6,0.2,Iris-setosa\n',
 '13,4.8,3.0,1.4,0.1,Iris-setosa\n',
 '14,4.3,3.0,1.1,0.1,Iris-setosa\n',
 '15,5.8,4.0,1.2,0.2,Iris-setosa\n',
 '16,5.7,4.4,1.5,0.4,Iris-setosa\n',
 '17,5.4,3.9,1.3,0.4,Iris-setosa\n',
 '18,5.1,3.5,1.4,0.3,Iris-setosa\n',
 '19,5.7,3.8,1.7,0.3,Iris-setosa\n',
 '20,5.1,3.8,1.5,0.3,Iris-setosa\n',
 '21,5.4,3.4,1.7,0.2,Iris-setosa\n',
 '22,5.1,3.7,1.5,0.4,Iris-setosa\n',
 '23,4.6,3.6,1.0,0.2,Iris-setosa\n',
 '24,5.1,3.3,1.7,0.5,Iris-setosa\n',
 '25,4.8,3.4,1.9,0.2,Iris-setosa\n',
 '26,5.0,3.0,1.6,0.2,Iris-setosa\n',
 '27,5.0,3.4,1.6,0.4,Iris-setosa\n',
 '28,5.2,3

# 4 Remoção de Novas Linhas

Crie uma nova lista numa variável de nome `d1` onde cada elemento de `d1` corresponda à versão do mesmo elemento em `d0`, removendo o caractere de nova linha `\n` que aparece ao final de cada item. Assegure-se de que cada elemento da lista `d1` seja uma string simples (dependendo como você fez o upload, pode acontecer dos elementos estarem codificados, então decodifique caso necessário).

In [ ]:
# Seu código aqui
d1 = []

for linha in d0:
  d1.append(linha[:-1])

In [ ]:
ok.check('e03_4.py')

In [ ]:
d1

['1,5.1,3.5,1.4,0.2,Iris-setosa',
 '2,4.9,3.0,1.4,0.2,Iris-setosa',
 '3,4.7,3.2,1.3,0.2,Iris-setosa',
 '4,4.6,3.1,1.5,0.2,Iris-setosa',
 '5,5.0,3.6,1.4,0.2,Iris-setosa',
 '6,5.4,3.9,1.7,0.4,Iris-setosa',
 '7,4.6,3.4,1.4,0.3,Iris-setosa',
 '8,5.0,3.4,1.5,0.2,Iris-setosa',
 '9,4.4,2.9,1.4,0.2,Iris-setosa',
 '10,4.9,3.1,1.5,0.1,Iris-setosa',
 '11,5.4,3.7,1.5,0.2,Iris-setosa',
 '12,4.8,3.4,1.6,0.2,Iris-setosa',
 '13,4.8,3.0,1.4,0.1,Iris-setosa',
 '14,4.3,3.0,1.1,0.1,Iris-setosa',
 '15,5.8,4.0,1.2,0.2,Iris-setosa',
 '16,5.7,4.4,1.5,0.4,Iris-setosa',
 '17,5.4,3.9,1.3,0.4,Iris-setosa',
 '18,5.1,3.5,1.4,0.3,Iris-setosa',
 '19,5.7,3.8,1.7,0.3,Iris-setosa',
 '20,5.1,3.8,1.5,0.3,Iris-setosa',
 '21,5.4,3.4,1.7,0.2,Iris-setosa',
 '22,5.1,3.7,1.5,0.4,Iris-setosa',
 '23,4.6,3.6,1.0,0.2,Iris-setosa',
 '24,5.1,3.3,1.7,0.5,Iris-setosa',
 '25,4.8,3.4,1.9,0.2,Iris-setosa',
 '26,5.0,3.0,1.6,0.2,Iris-setosa',
 '27,5.0,3.4,1.6,0.4,Iris-setosa',
 '28,5.2,3.5,1.5,0.2,Iris-setosa',
 '29,5.2,3.4,1.4,0.2,Iris-set

# 5 Separação por Vírgulas

Crie uma nova lista em uma variável de nome `d2` onde cada elemento dessa lista seja uma sublista contendo as strings correspondentes a cada dado da string original, usando a vírgula como separador.

Por exemplo, transforme isso:

`'14,4.3,3.0,1.1,0.1,Iris-setosa'`

nisso:

`['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa']`

Faça isso para todos elementos, na mesma ordem da lista original, gravando o resultado em `d2`.


In [ ]:
# Seu código aqui
d2 = []

for linha in d1:
  d2.append(linha.split(','))


In [ ]:
ok.check('e03_5.py')

In [ ]:
d2

[['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
 ['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
 ['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
 ['4', '4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
 ['5', '5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
 ['6', '5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
 ['7', '4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
 ['8', '5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
 ['9', '4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
 ['10', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
 ['11', '5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
 ['12', '4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
 ['13', '4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
 ['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
 ['15', '5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
 ['16', '5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
 ['17', '5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
 ['18', '5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
 ['19', '5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
 ['20', '5.1', '3.8',

# 6 Entradas de Treinamento

Crie uma matriz no formato `array` do NumPy, numa variável de nome `d3`, contendo todos os dados da segunda, terceira, quarta e quinta colunas de `d2` transformados para o formato ponto flutuante (convertendo de string para número). Não inclua nem a primeira coluna (que é o id), nem a última coluna nessa conversão. Essa será a matriz de entradas.

In [ ]:
import numpy as np

In [ ]:
# Escreva seu código aqui
d3 = np.zeros((total, 4))

for i, linha in enumerate(d2[0:]):
  _, sl, sw, pl, pw, sp = linha
  sl = float(sl)
  sw = float(sw)
  pl = float(pl)
  pw = float(pw)
  d3[i:] = np.array([sl, sw, pl, pw])


In [ ]:
ok.check('e03_6.py')

In [ ]:
d3

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

# 7 Saídas Desejadas

Crie um `array` do NumPy para as saídas desejadas, no formado _one-hot_. Para isso utilize as strings da última coluna de `d2`, verificando qual espécie de planta se refere cada string:

 `'Iris-setosa'` $\rightarrow$ `[1.0, 0.0, 0.0]`
 
 `'Iris-versicolor'` $\rightarrow$ `[0.0, 1.0, 0.0]`

 `'Iris-virginica'` $\rightarrow$ `[0.0, 0.0, 1.0]`

 Grave o resultado em um `array` do NumPy de nome `d4`, com o mesmo número de linhas de `d3`, onde cada linha de `d4` corresponde ao vetor _one-hot_ da saída desejada da respectiva linha de entradas de `d4`.

In [ ]:
# Escreva seu código aqui
d4 = np.zeros((total, 3))

for i, linha in enumerate(d2[0:]):
  _, sl, sw, pl, pw, sp = linha
  
  if sp == 'Iris-setosa':
    d4[i,:] = np.array([1, 0, 0])
  
  elif sp == 'Iris-versicolor':
    d4[i, :] = np.array([0, 1, 0])
  
  elif sp == 'Iris-virginica':
    d4[i, :] = np.array([0, 0, 1])

In [ ]:
ok.check('e03_7.py')

In [ ]:
d4

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
#outra maneira
# cat = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
#d4[i:] = (cat== sp).astype('float)

# 8 Normalização das Entradas

Encontre o valor máximo e mínimo para cada uma das quatro colunas da matriz de entradas. Normalize os valores das entradas no intervalo entre zero e um, salvando o resultado em um `array` do NumPy de nome `d5`.

In [ ]:
from sklearn import preprocessing

In [ ]:
# Escreva seu código aqui

d5 = np.zeros((total, 4))

d5 = (d3 - np.min(d3, axis=0))/(np.max(d3, axis=0) -np.min(d3, axis=0))

In [ ]:
ok.check('e03_8.py')

In [ ]:
d5

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

# 9 Embaralhamento dos Dados

Misture as linhas dos dados dos valores de entradas de treinamento contidos em `d5` de forma aleatória. Faça o mesmo com as linhas das saídas desejadas em `d4`, de forma a manter a correspondência entre ambos. Chame a `array` resultante de dados de treinamento embaralhado de `x` e a `array` correspondente de saídas desejadas de `y`.

In [ ]:
# Escreva seu código aqui
from sklearn.utils import shuffle

x, y = shuffle(d5, d4, random_state = 0)

In [ ]:
ok.check('e03_9.py')

# 10 Separação de Dados de Treinamento e Validação

Separe os pares de dados de treinamento e validação nas proporções 90%/10%, respectivamente. Chame a entrada e saída desejada dos pares de treinamento de `x_train` e `y_train`, e use os nomes `x_test` e `y_test` para os dados de validação. Os dados de validação devem corresponder às linhas finais dos pares de `array` originais `x` e `y`.

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# Escreva seu código aqui

x_train = x[:135]
x_test = x[135:]
y_train = y[:135]
y_test = y[135:]

In [ ]:
ok.check('e03_10.py')

In [ ]:
x_train

array([[0.41666667, 0.33333333, 0.69491525, 0.95833333],
       [0.47222222, 0.08333333, 0.50847458, 0.375     ],
       [0.33333333, 0.91666667, 0.06779661, 0.04166667],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.55555556, 0.54166667, 0.84745763, 1.        ],
       [0.19444444, 0.625     , 0.05084746, 0.08333333],
       [0.66666667, 0.45833333, 0.62711864, 0.58333333],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.5       , 0.33333333, 0.50847458, 0.5       ],
       [0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.5       , 0.375     , 0.62711864, 0.54166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.33333333, 0.25      ,

In [ ]:
y_train

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0