### Exercício Neurônio

In [ ]:
import numpy as np
from matplotlib import pyplot as plt

In [ ]:
def tang_hiperbolica(x):
  return np.tanh(x)

In [ ]:
class Neuronio:
  def __init__(self, w0, w1, w2, b):
    self.w0 = w0
    self.w1 = w1
    self.w2 = w2
    self.b = b

  def compute(self, a1, a2, a3):
    s = self.w0*a1 + self.w1*a2 + self.w2*a3 + self.b
    z = tang_hiperbolica(s)
    return z

In [ ]:
n = Neuronio(-1.0, 0.0, 1.0, -0.5)
n.compute(1.0, 2.0, 3.0)

0.9051482536448664

In [ ]:
n.compute(1.0, 20.0, 3.0)

0.9051482536448664

In [ ]:
### O peso de a2 é 0, ou seja, não muda nada

### Exercício Perceptron

In [ ]:
def sigmoid(x):
  return 1.0 / (1 + np.exp(-x))

In [ ]:
class Perceptron():
  def __init__(self, n_inputs=4, n_hidden=8, n_outputs=1):
    # Sinapses
    self.w_ih = np.array([[1.12,0.92,1.28],[-0.88,-1.02,-1.46],[1.06,0.63,0.38],[-1.5,-1.99,-2.31]])
    self.w_ho = np.array([[0.54,2.51,-1.81,5.15],[-6.22,-4.08,1.75,-3.47],[5.89,1.58,-1.72,-4.06]])
    # Biases
    self.b_hid = np.array([[-8.86],[+4.36],[-1.87],[+4.79]])
    self.b_out =  np.array([[-0.82],[0.76],[-1.35]])
  def compute(self, inputs):
    # Garante que a entrada seja um vetor coluna
    inputs = np.reshape(inputs,(len(inputs),1))
    # Calcula as ativações, camada por camada
    self.s_hid = np.dot(self.w_ih, inputs) + self.b_hid
    self.z_hid = sigmoid(self.s_hid)
    self.s_out = np.dot(self.w_ho, self.z_hid) + self.b_out
    self.z_out = sigmoid(self.s_out)
    return self.z_out

In [ ]:
p = Perceptron()
array1= [1, 1, 1]
array2= [2, 2, 2]
array3 = [3, 3, 3]

In [ ]:
np.around(p.compute(array1),2)

array([[0.8],
       [0.1],
       [0.1]])

In [ ]:
np.around(p.compute(array2),2)

array([[0.1],
       [0.8],
       [0.1]])

In [ ]:
np.around(p.compute(array3),2)

array([[0.1],
       [0.1],
       [0.8]])